### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by mightywomble** [linagora/linshare-docker#15]
The linshare_backend is throwing a java exception based on 

java.io.FileNotFoundException: /etc/linshare/id_rsa (No such file or directory)
java.io.FileNotFoundException: /etc/linshare/id_rsa.pub

Had a trawl through the code and instructions can't see where to put these.

**Comment by fmartin-linagora** [comment]
Hi,
If LinShare does not find these files, it will skip them.
What is the version of LinShare you are trying to use ?

**Comment by mightywomble** [comment]
I did a Git clone today of this repo and can assure you there is a rather epic java fail..

Where is it looking and is that volume mapped to a, place I can put the files?


David Field
http://tech.davidfield.co.uk

**Comment by fmartin-linagora** [comment]
So I cloned the repository and launch the master branch.
There is indeed an issue but not related to the id_rsa keys.

There is an issue with mongodb configuration : 

<pre>
linshare_backend     | Caused by: java.lang.IllegalArgumentException: Could not resolve at least one server of the replica set configuration! Validate
</pre>

**Comment by fmartin-linagora** [comment]
weird, I don't know why yet. I will look at it ASAP.
